#!/usr/bin/env sh
set -e
if [ -z "$SOURCE_PATH" ]; then
  SOURCE_PATH="$(readlink -f $(dirname ${0})/..)"
fi

VERSION=$(cat "${SOURCE_PATH}/PAUSE_CONTAINER_VERSION")
${ADD_DEPENDENCIES_CMD} \
  --container-image-dependencies \
  "{ \"name\": \"pause-container\", \"image_reference\": \"k8s.gcr.io/pause:${VERSION}\", \"version\": \"$VERSION\", \"labels\": [ { \"name\": \"cloud.gardener.cnudie/dso/scanning-hints/binary_id/v1\", \"value\": { \"policy\": \"skip\", \"comment\": \"pause-container is not accessible from outside k8s clusters and not interacted with from other containers or other systems\" } } ] }"

cp "${BASE_DEFINITION_PATH}" "${COMPONENT_DESCRIPTOR_PATH}"