#!/usr/bin/env sh
set -e
if [ -z "$SOURCE_PATH" ]; then
  SOURCE_PATH="$(readlink -f $(dirname ${0})/..)"
fi

VERSION=$(cat "${SOURCE_PATH}/PAUSE_CONTAINER_VERSION")
${ADD_DEPENDENCIES_CMD} \
  --container-image-dependencies \
  "{ \"name\": \"pause-container\", \"image_reference\": \"k8s.gcr.io/pause:${VERSION}\", \"version\": \"$VERSION\" }"

cp "${BASE_DEFINITION_PATH}" "${COMPONENT_DESCRIPTOR_PATH}"